### ISSUE TITLE
Accordion Plugin : First panel open settings has no effect

### ISSUE THREAD

**Issue by Julien-Blanc** [jrief/djangocms-cascade#90]
It has effect only when using angular-js templates, not when using standard templates.

Changing templates/cascade/bootstrap3/accordion.html to :

    <div id="cmsplugin_{{ instance.id }}_{{ forloop.counter0 }}" class="panel-collapse collapse{% if forloop.first and instance.glossary.first_is_open = "on" %} in{% endif %}">

(line 14)
fixes the issue.

**Comment by jrief** [comment]
I am fixing this on the deserializer, because it affected all Text fields (except TextArea) with quotes etc.

**Comment by jrief** [comment]
Fixed on master branch. Will be part of version 0.6.1.

**Comment by Julien-Blanc** [comment]
Seems to be an issue mistake here, apparently you fixed #89, but #90 (this one) is not fixed in current master. Do you want me to make a pull request for it ?

**Comment by jrief** [comment]
Ups sorry, I mixed up the issue numbers.

But  templates/cascade/bootstrap3/accordion.html is the standard template, the Angular template would be templates/cascade/bootstrap3/angular-ui/accordion.html, therefore I'm not sure what you mean.

The easiest thing would be to create a PR. Thanks

**Comment by Julien-Blanc** [comment]
Yes, that’s it. It works with angular templates, but not with standard bootstrap templates, so i fixed standard bootstrap template.

Here is the PR : https://github.com/jrief/djangocms-cascade/pull/91

As a side note, your fix for #89 works fine, thanks !
